import React, { useState } from 'react';
import { useNavigate } from "react-router-dom";

import './styleFiles/Vote_join.css';

const Vote_join = () => {
  const [inputValue, setInputValue] = useState('');
  const navigate = useNavigate();

  const meetingButton = () => {
    console.log(inputValue)
    if(inputValue == 'next')
      navigate('/start');
  }
  return (
    <div className='join'>
      <div className='banner'>Voting Join</div>
      <div className='meetingDiv'>
        <label> Meeting ID </label>
        <input name="myInput" value={inputValue} onChange={(e) => setInputValue(e.target.value)}/>
        <button type="button" onClick={meetingButton}>Enter</button>
      </div>
    </div>
  )
}
//Note: group ID autogenerated? sent via text/email?

export default Vote_join